//
//  TimeZoneNames.swift
//  
//
//  Created by Woodrow Melling on 8/12/23.
//

import Foundation

extension TimeZone {
    var displayName: String {
        TimeZone.knownTimeZoneDisplayNames[identifier] ?? identifier
    }

    static var knownTimeZoneDisplayNames: [String : String] = [
        "Africa/Abidjan": "Abidjan, Côte d'Ivoire",
        "Africa/Accra": "Accra, Ghana",
        "Africa/Addis_Ababa": "Addis Ababa, Ethiopia",
        "Africa/Algiers": "Algiers, Algeria",
        "Africa/Asmara": "Asmara, Eritrea",
        "Africa/Bamako": "Bamako, Mali",
        "Africa/Bangui": "Bangui, Central African Republic",
        "Africa/Banjul": "Banjul, Gambia",
        "Africa/Bissau": "Bissau, Guinea-Bissau",
        "Africa/Blantyre": "Blantyre, Malawi",
        "Africa/Brazzaville": "Brazzaville, Congo",
        "Africa/Bujumbura": "Bujumbura, Burundi",
        "Africa/Cairo": "Cairo, Egypt",
        "Africa/Casablanca": "Casablanca, Morocco",
        "Africa/Ceuta": "Ceuta, Spain",
        "Africa/Conakry": "Conakry, Guinea",
        "Africa/Dakar": "Dakar, Senegal",
        "Africa/Dar_es_Salaam": "Dar es Salaam, Tanzania",
        "Africa/Djibouti": "Djibouti, Djibouti",
        "Africa/Douala": "Douala, Cameroon",
        "Africa/El_Aaiun": "El Aaiun, Western Sahara",
        "Africa/Freetown": "Freetown, Sierra Leone",
        "Africa/Gaborone": "Gaborone, Botswana",
        "Africa/Harare": "Harare, Zimbabwe",
        "Africa/Johannesburg": "Johannesburg, South Africa",
        "Africa/Juba": "Juba, South Sudan",
        "Africa/Kampala": "Kampala, Uganda",
        "Africa/Khartoum": "Khartoum, Sudan",
        "Africa/Kigali": "Kigali, Rwanda",
        "Africa/Kinshasa": "Kinshasa, Congo (Kinshasa)",
        "Africa/Lagos": "Lagos, Nigeria",
        "Africa/Libreville": "Libreville, Gabon",
        "Africa/Lome": "Lome, Togo",
        "Africa/Luanda": "Luanda, Angola",
        "Africa/Lubumbashi": "Lubumbashi, Congo (Kinshasa)",
        "Africa/Lusaka": "Lusaka, Zambia",
        "Africa/Malabo": "Malabo, Equatorial Guinea",
        "Africa/Maputo": "Maputo, Mozambique",
        "Africa/Maseru": "Maseru, Lesotho",
        "Africa/Mbabane": "Mbabane, Eswatini",
        "Africa/Mogadishu": "Mogadishu, Somalia",
        "Africa/Monrovia": "Monrovia, Liberia",
        "Africa/Nairobi": "Nairobi, Kenya",
        "Africa/Ndjamena": "Ndjamena, Chad",
        "Africa/Niamey": "Niamey, Niger",
        "Africa/Nouakchott": "Nouakchott, Mauritania",
        "Africa/Ouagadougou": "Ouagadougou, Burkina Faso",
        "Africa/Porto-Novo": "Porto-Novo, Benin",
        "Africa/Sao_Tome": "Sao Tome, Sao Tome and Principe",
        "Africa/Tripoli": "Tripoli, Libya",
        "Africa/Tunis": "Tunis, Tunisia",
        "Africa/Windhoek": "Windhoek, Namibia",
        "America/Adak": "Adak, U.S.A",
        "America/Anchorage": "Anchorage, U.S.A",
        "America/Anguilla": "Anguilla",
        "America/Antigua": "Antigua",
        "America/Araguaina": "Araguaina, Brazil",
        "America/Argentina/Buenos_Aires": "Buenos Aires, Argentina",
        "America/Argentina/Catamarca": "Catamarca, Argentina",
        "America/Argentina/Cordoba": "Cordoba, Argentina",
        "America/Argentina/Jujuy": "Jujuy, Argentina",
        "America/Argentina/La_Rioja": "La Rioja, Argentina",
        "America/Argentina/Mendoza": "Mendoza, Argentina",
        "America/Argentina/Rio_Gallegos": "Rio Gallegos, Argentina",
        "America/Argentina/Salta": "Salta, Argentina",
        "America/Argentina/San_Juan": "San Juan, Argentina",
        "America/Argentina/San_Luis": "San Luis, Argentina",
        "America/Argentina/Tucuman": "Tucuman, Argentina",
        "America/Argentina/Ushuaia": "Ushuaia, Argentina",
        "America/Aruba": "Aruba",
        "America/Asuncion": "Asuncion, Paraguay",
        "America/Atikokan": "Atikokan, Canada",
        "America/Bahia": "Bahia, Brazil",
        "America/Bahia_Banderas": "Bahia Banderas, Mexico",
        "America/Barbados": "Barbados",
        "America/Belem": "Belem, Brazil",
        "America/Belize": "Belize",
        "America/Blanc-Sablon": "Blanc-Sablon, Canada",
        "America/Boa_Vista": "Boa Vista, Brazil",
        "America/Bogota": "Bogota, Colombia",
        "America/Boise": "Boise, U.S.A",
        "America/Cambridge_Bay": "Cambridge Bay, Canada",
        "America/Campo_Grande": "Campo Grande, Brazil",
        "America/Cancun": "Cancun, Mexico",
        "America/Caracas": "Caracas, Venezuela",
        "America/Cayenne": "Cayenne, French Guiana",
        "America/Cayman": "Cayman Islands",
        "America/Chicago": "Chicago, U.S.A",
        "America/Chihuahua": "Chihuahua, Mexico",
        "America/Costa_Rica": "Costa Rica",
        "America/Creston": "Creston, Canada",
        "America/Cuiaba": "Cuiaba, Brazil",
        "America/Curacao": "Curacao",
        "America/Danmarkshavn": "Danmarkshavn, Greenland",
        "America/Dawson": "Dawson, Canada",
        "America/Dawson_Creek": "Dawson Creek, Canada",
        "America/Denver": "Denver, U.S.A",
        "America/Detroit": "Detroit, U.S.A",
        "America/Dominica": "Dominica",
        "America/Edmonton": "Edmonton, Canada",
        "America/Eirunepe": "Eirunepe, Brazil",
        "America/El_Salvador": "El Salvador",
        "America/Fort_Nelson": "Fort Nelson, Canada",
        "America/Fortaleza": "Fortaleza, Brazil",
        "America/Glace_Bay": "Glace Bay, Canada",
        "America/Godthab": "Godthab, Greenland",
        "America/Goose_Bay": "Goose Bay, Canada",
        "America/Grand_Turk": "Grand Turk, Turks and Caicos Islands",
        "America/Grenada": "Grenada",
        "America/Guadeloupe": "Guadeloupe",
        "America/Guatemala": "Guatemala",
        "America/Guayaquil": "Guayaquil, Ecuador",
        "America/Guyana": "Guyana",
        "America/Halifax": "Halifax, Canada",
        "America/Havana": "Havana, Cuba",
        "America/Hermosillo": "Hermosillo, Mexico",
        "America/Indiana/Indianapolis": "Indianapolis, U.S.A",
        "America/Indiana/Knox": "Knox, U.S.A",
        "America/Indiana/Marengo": "Marengo, U.S.A",
        "America/Indiana/Petersburg": "Petersburg, U.S.A",
        "America/Indiana/Tell_City": "Tell City, U.S.A",
        "America/Indiana/Vevay": "Vevay, U.S.A",
        "America/Indiana/Vincennes": "Vincennes, U.S.A",
        "America/Indiana/Winamac": "Winamac, U.S.A",
        "America/Inuvik": "Inuvik, Canada",
        "America/Iqaluit": "Iqaluit, Canada",
        "America/Jamaica": "Jamaica",
        "America/Juneau": "Juneau, U.S.A",
        "America/Kentucky/Louisville": "Louisville, U.S.A",
        "America/Kentucky/Monticello": "Monticello, U.S.A",
        "America/Kralendijk": "Kralendijk, Bonaire, Sint Eustatius and Saba",
        "America/La_Paz": "La Paz, Bolivia",
        "America/Lima": "Lima, Peru",
        "America/Los_Angeles": "Los Angeles, U.S.A",
        "America/Lower_Princes": "Lower Prince's Quarter, Sint Maarten",
        "America/Maceio": "Maceio, Brazil",
        "America/Managua": "Managua, Nicaragua",
        "America/Manaus": "Manaus, Brazil",
        "America/Marigot": "Marigot, Saint Martin",
        "America/Martinique": "Martinique",
        "America/Matamoros": "Matamoros, Mexico",
        "America/Mazatlan": "Mazatlan, Mexico",
        "America/Menominee": "Menominee, U.S.A",
        "America/Merida": "Merida, Mexico",
        "America/Metlakatla": "Metlakatla, U.S.A",
        "America/Mexico_City": "Mexico City, Mexico",
        "America/Miquelon": "Miquelon, Saint Pierre and Miquelon",
        "America/Moncton": "Moncton, Canada",
        "America/Monterrey": "Monterrey, Mexico",
        "America/Montevideo": "Montevideo, Uruguay",
        "America/Montreal": "Montreal, Canada",
        "America/Montserrat": "Montserrat",
        "America/Nassau": "Nassau, Bahamas",
        "America/New_York": "New York, U.S.A",
        "America/Nipigon": "Nipigon, Canada",
        "America/Nome": "Nome, U.S.A",
        "America/Noronha": "Fernando de Noronha, Brazil",
        "America/North_Dakota/Beulah": "Beulah, U.S.A",
        "America/North_Dakota/Center": "Center, U.S.A",
        "America/North_Dakota/New_Salem": "New Salem, U.S.A",
        "America/Ojinaga": "Ojinaga, Mexico",
        "America/Panama": "Panama",
        "America/Pangnirtung": "Pangnirtung, Canada",
        "America/Paramaribo": "Paramaribo, Suriname",
        "America/Phoenix": "Phoenix, U.S.A",
        "America/Port-au-Prince": "Port-au-Prince, Haiti",
        "America/Port_of_Spain": "Port of Spain, Trinidad and Tobago",
        "America/Porto_Velho": "Porto Velho, Brazil",
        "America/Puerto_Rico": "Puerto Rico",
        "America/Rainy_River": "Rainy River, Canada",
        "America/Rankin_Inlet": "Rankin Inlet, Canada",
        "America/Recife": "Recife, Brazil",
        "America/Regina": "Regina, Canada",
        "America/Resolute": "Resolute, Canada",
        "America/Rio_Branco": "Rio Branco, Brazil",
        "America/Santa_Isabel": "Santa Isabel, Mexico",
        "America/Santarem": "Santarem, Brazil",
        "America/Santiago": "Santiago, Chile",
        "America/Santo_Domingo": "Santo Domingo, Dominican Republic",
        "America/Sao_Paulo": "Sao Paulo, Brazil",
        "America/Scoresbysund": "Scoresbysund, Greenland",
        "America/Shiprock": "Shiprock, U.S.A",
        "America/Sitka": "Sitka, U.S.A",
        "America/St_Barthelemy": "St. Barthelemy",
        "America/St_Johns": "St. John's, Canada",
        "America/St_Kitts": "St. Kitts",
        "America/St_Lucia": "St. Lucia",
        "America/St_Thomas": "St. Thomas, U.S. Virgin Islands",
        "America/St_Vincent": "St. Vincent",
        "America/Swift_Current": "Swift Current, Canada",
        "America/Tegucigalpa": "Tegucigalpa, Honduras",
        "America/Thule": "Thule, Greenland",
        "America/Thunder_Bay": "Thunder Bay, Canada",
        "America/Tijuana": "Tijuana, Mexico",
        "America/Toronto": "Toronto, Canada",
        "America/Tortola": "Tortola, British Virgin Islands",
        "America/Vancouver": "Vancouver, Canada",
        "America/Whitehorse": "Whitehorse, Canada",
        "America/Winnipeg": "Winnipeg, Canada",
        "America/Yakutat": "Yakutat, U.S.A",
        "America/Yellowknife": "Yellowknife, Canada",
        "Antarctica/Casey": "Casey, Antarctica",
        "Antarctica/Davis": "Davis, Antarctica",
        "Antarctica/DumontDUrville": "Dumont d'Urville, Antarctica",
        "Antarctica/Macquarie": "Macquarie Island, Australia",
        "Antarctica/Mawson": "Mawson, Antarctica",
        "Antarctica/McMurdo": "McMurdo, Antarctica",
        "Antarctica/Palmer": "Palmer, Antarctica",
        "Antarctica/Rothera": "Rothera, Antarctica",
        "Antarctica/South_Pole": "South Pole, Antarctica",
        "Antarctica/Syowa": "Syowa, Antarctica",
        "Antarctica/Troll": "Troll Station, Antarctica",
        "Antarctica/Vostok": "Vostok, Antarctica",
        "Arctic/Longyearbyen": "Longyearbyen, Svalbard and Jan Mayen",
        "Asia/Aden": "Aden, Yemen",
        "Asia/Almaty": "Almaty, Kazakhstan",
        "Asia/Amman": "Amman, Jordan",
        "Asia/Anadyr": "Anadyr, Russia",
        "Asia/Aqtau": "Aqtau, Kazakhstan",
        "Asia/Aqtobe": "Aqtobe, Kazakhstan",
        "Asia/Ashgabat": "Ashgabat, Turkmenistan",
        "Asia/Baghdad": "Baghdad, Iraq",
        "Asia/Bahrain": "Bahrain",
        "Asia/Baku": "Baku, Azerbaijan",
        "Asia/Bangkok": "Bangkok, Thailand",
        "Asia/Barnaul": "Barnaul, Russia",
        "Asia/Beirut": "Beirut, Lebanon",
        "Asia/Bishkek": "Bishkek, Kyrgyzstan",
        "Asia/Brunei": "Brunei",
        "Asia/Chita": "Chita, Russia",
        "Asia/Choibalsan": "Choibalsan, Mongolia",
        "Asia/Chongqing": "Chongqing, China",
        "Asia/Colombo": "Colombo, Sri Lanka",
        "Asia/Damascus": "Damascus, Syria",
        "Asia/Dhaka": "Dhaka, Bangladesh",
        "Asia/Dili": "Dili, Timor-Leste",
        "Asia/Dubai": "Dubai, United Arab Emirates",
        "Asia/Dushanbe": "Dushanbe, Tajikistan",
        "Asia/Gaza": "Gaza, Palestinian Territories",
        "Asia/Harbin": "Harbin, China",
        "Asia/Hebron": "Hebron, Palestinian Territories",
        "Asia/Ho_Chi_Minh": "Ho Chi Minh City, Vietnam",
        "Asia/Hong_Kong": "Hong Kong",
        "Asia/Hovd": "Hovd, Mongolia",
        "Asia/Irkutsk": "Irkutsk, Russia",
        "Asia/Jakarta": "Jakarta, Indonesia",
        "Asia/Jayapura": "Jayapura, Indonesia",
        "Asia/Jerusalem": "Jerusalem, Israel",
        "Asia/Kabul": "Kabul, Afghanistan",
        "Asia/Kamchatka": "Kamchatka, Russia",
        "Asia/Karachi": "Karachi, Pakistan",
        "Asia/Kashgar": "Kashgar, China",
        "Asia/Kathmandu": "Kathmandu, Nepal",
        "Asia/Katmandu": "Kathmandu, Nepal",
        "Asia/Khandyga": "Khandyga, Russia",
        "Asia/Kolkata": "Kolkata, India",
        "Asia/Krasnoyarsk": "Krasnoyarsk, Russia",
        "Asia/Kuala_Lumpur": "Kuala Lumpur, Malaysia",
        "Asia/Kuching": "Kuching, Malaysia",
        "Asia/Kuwait": "Kuwait",
        "Asia/Macau": "Macau",
        "Asia/Magadan": "Magadan, Russia",
        "Asia/Makassar": "Makassar, Indonesia",
        "Asia/Manila": "Manila, Philippines",
        "Asia/Muscat": "Muscat, Oman",
        "Asia/Nicosia": "Nicosia, Cyprus",
        "Asia/Novokuznetsk": "Novokuznetsk, Russia",
        "Asia/Novosibirsk": "Novosibirsk, Russia",
        "Asia/Omsk": "Omsk, Russia",
        "Asia/Oral": "Oral, Kazakhstan",
        "Asia/Phnom_Penh": "Phnom Penh, Cambodia",
        "Asia/Pontianak": "Pontianak, Indonesia",
        "Asia/Pyongyang": "Pyongyang, North Korea",
        "Asia/Qatar": "Qatar",
        "Asia/Qyzylorda": "Qyzylorda, Kazakhstan",
        "Asia/Rangoon": "Rangoon, Myanmar",
        "Asia/Riyadh": "Riyadh, Saudi Arabia",
        "Asia/Sakhalin": "Sakhalin, Russia",
        "Asia/Samarkand": "Samarkand, Uzbekistan",
        "Asia/Seoul": "Seoul, South Korea",
        "Asia/Shanghai": "Shanghai, China",
        "Asia/Singapore": "Singapore",
        "Asia/Srednekolymsk": "Srednekolymsk, Russia",
        "Asia/Taipei": "Taipei, Taiwan",
        "Asia/Tashkent": "Tashkent, Uzbekistan",
        "Asia/Tbilisi": "Tbilisi, Georgia",
        "Asia/Tehran": "Tehran, Iran",
        "Asia/Thimphu": "Thimphu, Bhutan",
        "Asia/Tokyo": "Tokyo, Japan",
        "Asia/Tomsk": "Tomsk, Russia",
        "Asia/Ulaanbaatar": "Ulaanbaatar, Mongolia",
        "Asia/Urumqi": "Urumqi, China",
        "Asia/Ust-Nera": "Ust-Nera, Russia",
        "Asia/Vientiane": "Vientiane, Laos",
        "Asia/Vladivostok": "Vladivostok, Russia",
        "Asia/Yakutsk": "Yakutsk, Russia",
        "Asia/Yangon": "Yangon, Myanmar",
        "Asia/Yekaterinburg": "Yekaterinburg, Russia",
        "Asia/Yerevan": "Yerevan, Armenia",
        "Atlantic/Azores": "Azores, Portugal",
        "Atlantic/Bermuda": "Bermuda",
        "Atlantic/Canary": "Canary Islands, Spain",
        "Atlantic/Cape_Verde": "Cape Verde",
        "Atlantic/Faroe": "Faroe Islands, Denmark",
        "Atlantic/Madeira": "Madeira, Portugal",
        "Atlantic/Reykjavik": "Reykjavik, Iceland",
        "Atlantic/South_Georgia": "South Georgia, South Georgia and the South Sandwich Islands",
        "Atlantic/St_Helena": "St. Helena",
        "Atlantic/Stanley": "Stanley, Falkland Islands",
        "Australia/Adelaide": "Adelaide, Australia",
        "Australia/Brisbane": "Brisbane, Australia",
        "Australia/Broken_Hill": "Broken Hill, Australia",
        "Australia/Currie": "Currie, Australia",
        "Australia/Darwin": "Darwin, Australia",
        "Australia/Eucla": "Eucla, Australia",
        "Australia/Hobart": "Hobart, Australia",
        "Australia/Lindeman": "Lindeman, Australia",
        "Australia/Lord_Howe": "Lord Howe Island, Australia",
        "Australia/Melbourne": "Melbourne, Australia",
        "Australia/Perth": "Perth, Australia",
        "Australia/Sydney": "Sydney, Australia",
        "Europe/Amsterdam": "Amsterdam, Netherlands",
        "Europe/Andorra": "Andorra",
        "Europe/Astrakhan": "Astrakhan, Russia",
        "Europe/Athens": "Athens, Greece",
        "Europe/Belgrade": "Belgrade, Serbia",
        "Europe/Berlin": "Berlin, Germany",
        "Europe/Bratislava": "Bratislava, Slovakia",
        "Europe/Brussels": "Brussels, Belgium",
        "Europe/Bucharest": "Bucharest, Romania",
        "Europe/Budapest": "Budapest, Hungary",
        "Europe/Busingen": "Busingen, Germany",
        "Europe/Chisinau": "Chisinau, Moldova",
        "Europe/Copenhagen": "Copenhagen, Denmark",
        "Europe/Dublin": "Dublin, Ireland",
        "Europe/Gibraltar": "Gibraltar",
        "Europe/Guernsey": "Guernsey",
        "Europe/Helsinki": "Helsinki, Finland",
        "Europe/Isle_of_Man": "Isle of Man",
        "Europe/Istanbul": "Istanbul, Turkey",
        "Europe/Jersey": "Jersey",
        "Europe/Kaliningrad": "Kaliningrad, Russia",
        "Europe/Kiev": "Kiev, Ukraine",
        "Europe/Kirov": "Kirov, Russia",
        "Europe/Lisbon": "Lisbon, Portugal",
        "Europe/Ljubljana": "Ljubljana, Slovenia",
        "Europe/London": "London, United Kingdom",
        "Europe/Luxembourg": "Luxembourg",
        "Europe/Madrid": "Madrid, Spain",
        "Europe/Malta": "Malta",
        "Europe/Mariehamn": "Mariehamn, Aland Islands",
        "Europe/Minsk": "Minsk, Belarus",
        "Europe/Monaco": "Monaco",
        "Europe/Moscow": "Moscow, Russia",
        "Europe/Oslo": "Oslo, Norway",
        "Europe/Paris": "Paris, France",
        "Europe/Podgorica": "Podgorica, Montenegro",
        "Europe/Prague": "Prague, Czech Republic",
        "Europe/Riga": "Riga, Latvia",
        "Europe/Rome": "Rome, Italy",
        "Europe/Samara": "Samara, Russia",
        "Europe/San_Marino": "San Marino",
        "Europe/Sarajevo": "Sarajevo, Bosnia and Herzegovina",
        "Europe/Saratov": "Saratov, Russia",
        "Europe/Simferopol": "Simferopol, Russia",
        "Europe/Skopje": "Skopje, North Macedonia",
        "Europe/Sofia": "Sofia, Bulgaria",
        "Europe/Stockholm": "Stockholm, Sweden",
        "Europe/Tallinn": "Tallinn, Estonia",
        "Europe/Tirane": "Tirane, Albania",
        "Europe/Ulyanovsk": "Ulyanovsk, Russia",
        "Europe/Uzhgorod": "Uzhgorod, Ukraine",
        "Europe/Vaduz": "Vaduz, Liechtenstein",
        "Europe/Vatican": "Vatican City",
        "Europe/Vienna": "Vienna, Austria",
        "Europe/Vilnius": "Vilnius, Lithuania",
        "Europe/Volgograd": "Volgograd, Russia",
        "Europe/Warsaw": "Warsaw, Poland",
        "Europe/Zagreb": "Zagreb, Croatia",
        "Europe/Zaporozhye": "Zaporozhye, Ukraine",
        "Europe/Zurich": "Zurich, Switzerland",
        "Indian/Antananarivo": "Antananarivo, Madagascar",
        "Indian/Chagos": "Chagos, British Indian Ocean Territory",
        "Indian/Christmas": "Christmas Island, Australia",
        "Indian/Cocos": "Cocos Islands, Australia",
        "Indian/Comoro": "Comoro",
        "Indian/Kerguelen": "Kerguelen, French Southern Territories",
        "Indian/Mahe": "Mahe, Seychelles",
        "Indian/Maldives": "Maldives",
        "Indian/Mauritius": "Mauritius",
        "Indian/Mayotte": "Mayotte",
        "Indian/Reunion": "Reunion",
        "Pacific/Apia": "Apia, Samoa",
        "Pacific/Auckland": "Auckland, New Zealand",
        "Pacific/Bougainville": "Bougainville, Papua New Guinea",
        "Pacific/Chatham": "Chatham Islands, New Zealand",
        "Pacific/Chuuk": "Chuuk, Micronesia",
        "Pacific/Easter": "Easter Island, Chile",
        "Pacific/Efate": "Efate, Vanuatu",
        "Pacific/Enderbury": "Enderbury, Kiribati",
        "Pacific/Fakaofo": "Fakaofo, Tokelau",
        "Pacific/Fiji": "Fiji",
        "Pacific/Funafuti": "Funafuti, Tuvalu",
        "Pacific/Galapagos": "Galapagos Islands, Ecuador",
        "Pacific/Gambier": "Gambier Islands, French Polynesia",
        "Pacific/Guadalcanal": "Guadalcanal, Solomon Islands",
        "Pacific/Guam": "Guam",
        "Pacific/Honolulu": "Honolulu, U.S.A",
        "Pacific/Kiritimati": "Kiritimati, Kiribati",
        "Pacific/Kosrae": "Kosrae, Micronesia",
        "Pacific/Kwajalein": "Kwajalein, Marshall Islands",
        "Pacific/Majuro": "Majuro, Marshall Islands",
        "Pacific/Marquesas": "Marquesas Islands, French Polynesia",
        "Pacific/Midway": "Midway, U.S.A",
        "Pacific/Nauru": "Nauru",
        "Pacific/Niue": "Niue",
        "Pacific/Norfolk": "Norfolk Island, Australia",
        "Pacific/Noumea": "Noumea, New Caledonia",
        "Pacific/Pago_Pago": "Pago Pago, American Samoa",
        "Pacific/Palau": "Palau",
        "Pacific/Pitcairn": "Pitcairn Islands",
        "Pacific/Pohnpei": "Pohnpei, Micronesia",
        "Pacific/Port_Moresby": "Port Moresby, Papua New Guinea",
        "Pacific/Rarotonga": "Rarotonga, Cook Islands",
        "Pacific/Saipan": "Saipan, Northern Mariana Islands",
        "Pacific/Tahiti": "Tahiti, French Polynesia",
        "Pacific/Tarawa": "Tarawa, Kiribati",
        "Pacific/Tongatapu": "Tongatapu, Tonga",
        "Pacific/Wake": "Wake Island, U.S.A",
        "Pacific/Wallis": "Wallis and Futuna",
        "UTC": "Coordinated Universal Time (UTC)"
    ]
}
